sudo: false
dist: trusty
language: node_js
branches:
  only:
    - master
cache:
  directories:
    - node_modules
after_success:
  - npm run eslint
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
  - npm run build
deploy:
  - provider: gae
    skip-cleanup: true
    keyfile: gae-service-account.json
    project: geofiddle-224910
    default: true
    no_promote: false
    verbosity: info
  - provider: pages
    skip-cleanup: true
    local-dir: ./dist
    target-branch: gh-pages
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: false
    on:
      branch: master
before_install:
  - openssl aes-256-cbc -K $encrypted_cb57a5ee4bf1_key -iv $encrypted_cb57a5ee4bf1_iv
    -in gae-service-account.json.enc -out gae-service-account.json -d
