runtime: go111

default_expiration: "7d"

handlers:

# Base web resources
- url: /(browserconfig\.xml)
  static_files: static/\1
  upload: static/browserconfig\.xml
- url: /(favicon\.ico)
  static_files: static/\1
  upload: static/favicon\.ico
- url: /(humans\.txt)
  static_files: static/\1
  upload: static/humans\.txt
- url: /(icon\.png)
  static_files: static/\1
  upload: static/icon\.png
- url: /(robots\.txt)
  static_files: static/\1
  upload: static/robots\.txt
- url: /(site\.webmanifest)
  static_files: static/\1
  upload: static/site\.webmanifest
- url: /(tile-wide\.png)
  static_files: static/\1
  upload: static/tile-wide\.png
- url: /(tile\.png)
  static_files: static/\1
  upload: static/tile\.png

# Generated resources (html, js, etc.)
- url: /dist
  static_dir: dist

# Fallback to main.go
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
